import type { AlignmentResult } from "./types"

export function generateLatexResume(
  result: AlignmentResult,
  userProfile: {
    name: string
    email: string
    phone: string
    location: string
    website?: string
    linkedin?: string
    github?: string
  }
): string {
  const { resume } = result

  // Escape special LaTeX characters
  const escape = (str: string) => {
    return str
      .replace(/\\/g, "\\textbackslash{}")
      .replace(/([&%$#_{}~^])/g, "\\$1")
      .replace(/\textbackslash\{\}/g, "\\textbackslash{}")
  }

  // Build contact links
  let contactLinks = `\\small ${escape(userProfile.phone)}`
  if (userProfile.website) {
    contactLinks += ` $|$ \\href{https://${escape(userProfile.website)}}{\\underline{${escape(userProfile.website)}}}`
  }
  if (userProfile.email) {
    contactLinks += ` $|$ \\href{mailto:${escape(userProfile.email)}}{\\underline{${escape(userProfile.email)}}}`
  }
  if (userProfile.linkedin) {
    contactLinks += ` $|$ \\href{https://linkedin.com/in/${escape(userProfile.linkedin)}}{\\underline{linkedin.com/in/${escape(userProfile.linkedin)}}}`
  }
  if (userProfile.github) {
    contactLinks += ` $|$ \\href{https://github.com/${escape(userProfile.github)}}{\\underline{github.com/${escape(userProfile.github)}}}`
  }

  // Build technical skills section
  const skillsByCategory = new Map<string, string[]>()
  resume.coreSkills.forEach((skill) => {
    // Simple categorization - can be enhanced
    const category = "Technical Skills"
    if (!skillsByCategory.has(category)) {
      skillsByCategory.set(category, [])
    }
    skillsByCategory.get(category)!.push(escape(skill))
  })

  let skillsContent = ""
  Array.from(skillsByCategory.entries()).forEach(([category, skills], idx) => {
    skillsContent += `\\textbf{${escape(category)}:} ${skills.join(", ")}`
    if (idx < skillsByCategory.size - 1) skillsContent += "\\\\\n     "
  })

  // Build experience section
  let experienceContent = ""
  resume.experiences.forEach((exp, idx) => {
    experienceContent += `    \\resumeSubheading\n      {${escape(exp.company)} -- ${exp.period}}{}\n      {${escape(exp.role)}}{}\n`
    experienceContent += `      \\resumeItemListStart\n`
    exp.bullets.forEach((bullet) => {
      const bulletText = escape(bullet.text)
      if (bullet.emphasized) {
        experienceContent += `        \\resumeItem{\\textbf{${bulletText}} \\small\\textcolor{custom2}{[JD MATCH]}}\n`
      } else {
        experienceContent += `        \\resumeItem{${bulletText}}\n`
      }
    })
    experienceContent += `      \\resumeItemListEnd\n`
    if (idx < resume.experiences.length - 1) experienceContent += "\n"
  })

  const latex = `%-------------------------
% ATS-Optimized Resume in LaTeX (Generated by Semantic Career Alignment Engine)
%------------------------

\\documentclass[letterpaper,11pt]{article}

\\usepackage{latexsym}
\\usepackage[empty]{fullpage}
\\usepackage{titlesec}
\\usepackage{marvosym}
\\usepackage[usenames,dvipsnames]{color}
\\usepackage{verbatim}
\\usepackage{enumitem}
\\usepackage[hidelinks]{hyperref}
\\usepackage{fancyhdr}
\\usepackage[english]{babel}
\\usepackage{tabularx}
\\usepackage{multicol}
\\setlength{\\multicolsep}{-3.0pt}
\\setlength{\\columnsep}{-1pt}
\\input{glyphtounicode}

\\definecolor{custom1}{RGB}{10, 48, 97}
\\definecolor{custom2}{RGB}{65,105,225}

\\pagestyle{fancy}
\\fancyhf{} % clear all header and footer fields
\\fancyfoot{}
\\renewcommand{\\headrulewidth}{0pt}
\\renewcommand{\\footrulewidth}{0pt}

% Adjust margins
\\addtolength{\\oddsidemargin}{-0.6in}
\\addtolength{\\evensidemargin}{-0.5in}
\\addtolength{\\textwidth}{1.19in}
\\addtolength{\\topmargin}{-.7in}
\\addtolength{\\textheight}{1.4in}

\\urlstyle{same}

\\raggedbottom
\\raggedright
\\setlength{\\tabcolsep}{0in}

% Sections formatting
\\titleformat{\\section}{
  \\vspace{-4pt}\\scshape\\raggedright\\large\\bfseries
}{}{0em}{}[\\titlerule \\vspace{-5pt}]

% Ensure that generated pdf is machine readable/ATS parsable
\\pdfgentounicode=1

%-------------------------
% Custom commands
\\newcommand{\\resumeItem}[1]{
  \\item\\small{
    {#1 \\vspace{-2pt}}
  }
}

\\newcommand{\\resumeSubheading}[4]{
  \\vspace{-2pt}\\item
    \\begin{tabular*}{1.0\\textwidth}[t]{l@{\\extracolsep{\\fill}}r}
      \\textbf{{#1}} & \\textbf{\\small #2} \\\\
      \\textit{\\small#3} & \\textit{\\small #4} \\\\
    \\end{tabular*}\\vspace{-7pt}
}

\\newcommand{\\resumeProjectHeading}[2]{
    \\item
    \\begin{tabular*}{1.001\\textwidth}{l@{\\extracolsep{\\fill}}r}
      \\small#1 & \\textbf{\\small #2}\\\\
    \\end{tabular*}\\vspace{-7pt}
}

\\renewcommand\\labelitemi{$$\\vcenter{\\hbox{\\tiny$$\\bullet$$}}$$}
\\renewcommand\\labelitemii{$$\\vcenter{\\hbox{\\tiny$$\\bullet$$}}$$}

\\newcommand{\\resumeSubHeadingListStart}{\\begin{itemize}[leftmargin=0.0in, label={}]}
\\newcommand{\\resumeSubHeadingListEnd}{\\end{itemize}}
\\newcommand{\\resumeItemListStart}{\\begin{itemize}}
\\newcommand{\\resumeItemListEnd}{\\end{itemize}\\vspace{-5pt}}

%-------------------------------------------
%%%%%%  RESUME STARTS HERE  %%%%%%%%%%%%%%%%%%%%%%%%%%%%

\\begin{document}

%----------HEADING----------
\\begin{center}
    {\\LARGE \\scshape \\textcolor{custom1}{${escape(userProfile.name)}}} \\\\ \\vspace{1pt}
    ${escape(userProfile.location)}  \\\\ \\vspace{3pt}
    ${contactLinks}
    \\vspace{-5pt}
\\end{center}

%-----------PROFESSIONAL SUMMARY-----------
\\section{\\textcolor{custom1}{Professional Summary}}
    \\resumeSubHeadingListStart
    \\small{${escape(resume.summary)}}
    \\resumeSubHeadingListEnd

%-----------TECHNICAL SKILLS-----------
\\vspace{-13pt}
\\section{\\textcolor{custom1}{Technical Skills}}
 \\begin{itemize}[leftmargin=0.15in, label={}]
    \\small{\\item{
     ${skillsContent} \\\\
     }}
 \\end{itemize}

%-----------PROFESSIONAL EXPERIENCE-----------
\\vspace{-13pt}
\\section{\\textcolor{custom1}{Professional Experience}}
  \\resumeSubHeadingListStart
${experienceContent}
  \\resumeSubHeadingListEnd

\\end{document}
`

  return latex
}

export function downloadLatex(content: string, filename: string = "resume.tex"): void {
  const element = document.createElement("a")
  element.setAttribute("href", "data:text/plain;charset=utf-8," + encodeURIComponent(content))
  element.setAttribute("download", filename)
  element.style.display = "none"
  document.body.appendChild(element)
  element.click()
  document.body.removeChild(element)
}

export async function generatePdfFromHtml(htmlElement: HTMLElement, filename: string = "resume.pdf"): Promise<void> {
  const { jsPDF } = await import("jspdf")
  const html2canvas = (await import("html2canvas")).default

  try {
    const canvas = await html2canvas(htmlElement, {
      scale: 2,
      useCORS: true,
      logging: false,
      backgroundColor: "#ffffff",
      windowHeight: htmlElement.scrollHeight,
    })

    const imgData = canvas.toDataURL("image/png")
    const pdf = new jsPDF({
      orientation: "portrait",
      unit: "mm",
      format: "a4",
    })

    const imgWidth = 210 // A4 width in mm
    const imgHeight = (canvas.height * imgWidth) / canvas.width
    const pageHeight = 297 // A4 height in mm
    let heightLeft = imgHeight
    let position = 0

    pdf.addImage(imgData, "PNG", 0, position, imgWidth, imgHeight)
    heightLeft -= pageHeight

    while (heightLeft >= 0) {
      position = heightLeft - imgHeight
      pdf.addPage()
      pdf.addImage(imgData, "PNG", 0, position, imgWidth, imgHeight)
      heightLeft -= pageHeight
    }

    pdf.save(filename)
  } catch (error) {
    console.error("[v0] PDF generation error:", error)
    throw error
  }
}
