import type { AlignmentResult } from "./types"

// Escape special LaTeX characters.
function escapeLatex(str: string): string {
  return str
    .replace(/\\/g, "\\textbackslash{}")
    .replace(/([&%$#_{}])/g, "\\$1")
    .replace(/~/g, "\\textasciitilde{}")
    .replace(/\^/g, "\\textasciicircum{}")
}

/**
 * Generate an ATS-optimized LaTeX resume that mirrors the user's template.
 * Personal/contact details are intentionally omitted.
 */
export function generateLatexResume(result: AlignmentResult): string {
  const { resume } = result

  // Split skills into two categories so the section reads cleanly.
  const half = Math.ceil(resume.coreSkills.length / 2)
  const primarySkills = resume.coreSkills.slice(0, half).map(escapeLatex).join(", ")
  const secondarySkills = resume.coreSkills.slice(half).map(escapeLatex).join(", ")

  let skillsContent = ""
  if (primarySkills) {
    skillsContent += `\\textbf{Core Competencies:} ${primarySkills}`
    if (secondarySkills) skillsContent += " \\\\\n     "
  }
  if (secondarySkills) {
    skillsContent += `\\textbf{Supporting Skills:} ${secondarySkills}`
  }

  // Build experience entries.
  let experienceContent = ""
  resume.experiences.forEach((exp) => {
    experienceContent += `    \\resumeSubheading\n      {${escapeLatex(exp.company)}}{${escapeLatex(exp.period)}}\n      {${escapeLatex(exp.role)}}{}\n`
    experienceContent += `      \\resumeItemListStart\n`
    exp.bullets.forEach((bullet) => {
      const text = escapeLatex(bullet.text)
      experienceContent += bullet.emphasized
        ? `        \\resumeItem{\\textcolor{custom2}{${text}}}\n`
        : `        \\resumeItem{${text}}\n`
    })
    experienceContent += `      \\resumeItemListEnd\n`
  })

  return `%-------------------------
% ATS-Optimized Resume in LaTeX
% Generated by Semantic Career Alignment Engine
%------------------------

\\documentclass[letterpaper,11pt]{article}

\\usepackage{latexsym}
\\usepackage[empty]{fullpage}
\\usepackage{titlesec}
\\usepackage{marvosym}
\\usepackage[usenames,dvipsnames]{color}
\\usepackage{verbatim}
\\usepackage{enumitem}
\\usepackage[hidelinks]{hyperref}
\\usepackage{fancyhdr}
\\usepackage[english]{babel}
\\usepackage{tabularx}
\\usepackage{multicol}
\\setlength{\\multicolsep}{-3.0pt}
\\setlength{\\columnsep}{-1pt}
\\input{glyphtounicode}

\\definecolor{custom1}{RGB}{10, 48, 97}
\\definecolor{custom2}{RGB}{65,105,225}

\\pagestyle{fancy}
\\fancyhf{}
\\fancyfoot{}
\\renewcommand{\\headrulewidth}{0pt}
\\renewcommand{\\footrulewidth}{0pt}

\\addtolength{\\oddsidemargin}{-0.6in}
\\addtolength{\\evensidemargin}{-0.5in}
\\addtolength{\\textwidth}{1.19in}
\\addtolength{\\topmargin}{-.7in}
\\addtolength{\\textheight}{1.4in}

\\urlstyle{same}

\\raggedbottom
\\raggedright
\\setlength{\\tabcolsep}{0in}

\\titleformat{\\section}{
  \\vspace{-4pt}\\scshape\\raggedright\\large\\bfseries
}{}{0em}{}[\\titlerule \\vspace{-5pt}]

\\pdfgentounicode=1

%-------------------------
% Custom commands
\\newcommand{\\resumeItem}[1]{
  \\item\\small{
    {#1 \\vspace{-2pt}}
  }
}

\\newcommand{\\resumeSubheading}[4]{
  \\vspace{-2pt}\\item
    \\begin{tabular*}{1.0\\textwidth}[t]{l@{\\extracolsep{\\fill}}r}
      \\textbf{{#1}} & \\textbf{\\small #2} \\\\
      \\textit{\\small#3} & \\textit{\\small #4} \\\\
    \\end{tabular*}\\vspace{-7pt}
}

\\renewcommand\\labelitemi{$$\\vcenter{\\hbox{\\tiny$$\\bullet$$}}$$}
\\renewcommand\\labelitemii{$$\\vcenter{\\hbox{\\tiny$$\\bullet$$}}$$}

\\newcommand{\\resumeSubHeadingListStart}{\\begin{itemize}[leftmargin=0.0in, label={}]}
\\newcommand{\\resumeSubHeadingListEnd}{\\end{itemize}}
\\newcommand{\\resumeItemListStart}{\\begin{itemize}}
\\newcommand{\\resumeItemListEnd}{\\end{itemize}\\vspace{-5pt}}

%-------------------------------------------
%%%%%%  RESUME STARTS HERE  %%%%%%%%%%%%%%%%%%%%%%%%%%%%

\\begin{document}

%----------HEADING----------
\\begin{center}
    {\\LARGE \\scshape \\textcolor{custom1}{${escapeLatex(resume.name)}}} \\\\ \\vspace{2pt}
    \\small ${escapeLatex(resume.headline)}
    \\vspace{-5pt}
\\end{center}

%-----------PROFESSIONAL SUMMARY-----------
\\section{\\textcolor{custom1}{Professional Summary}}
    \\resumeSubHeadingListStart
    \\small{${escapeLatex(resume.summary)}}
    \\resumeSubHeadingListEnd

%-----------TECHNICAL SKILLS-----------
\\vspace{-13pt}
\\section{\\textcolor{custom1}{Technical Skills}}
 \\begin{itemize}[leftmargin=0.15in, label={}]
    \\small{\\item{
     ${skillsContent} \\\\
     }}
 \\end{itemize}

%-----------PROFESSIONAL EXPERIENCE-----------
\\vspace{-13pt}
\\section{\\textcolor{custom1}{Professional Experience}}
  \\resumeSubHeadingListStart
${experienceContent}  \\resumeSubHeadingListEnd

\\end{document}
`
}

export function downloadLatex(content: string, filename = "resume.tex"): void {
  const element = document.createElement("a")
  element.setAttribute("href", "data:text/plain;charset=utf-8," + encodeURIComponent(content))
  element.setAttribute("download", filename)
  element.style.display = "none"
  document.body.appendChild(element)
  element.click()
  document.body.removeChild(element)
}

export async function generatePdfFromHtml(htmlElement: HTMLElement, filename = "resume.pdf"): Promise<void> {
  const { jsPDF } = await import("jspdf")
  const html2canvas = (await import("html2canvas")).default

  const canvas = await html2canvas(htmlElement, {
    scale: 2,
    useCORS: true,
    logging: false,
    backgroundColor: "#ffffff",
    windowHeight: htmlElement.scrollHeight,
  })

  const imgData = canvas.toDataURL("image/png")
  const pdf = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" })

  const pageWidth = 210 // A4 width in mm
  const pageHeight = 297 // A4 height in mm
  const imgWidth = pageWidth
  const imgHeight = (canvas.height * imgWidth) / canvas.width

  // Scale down to keep the resume on a single page when slightly over.
  if (imgHeight <= pageHeight + 8) {
    const finalHeight = Math.min(imgHeight, pageHeight)
    pdf.addImage(imgData, "PNG", 0, 0, imgWidth, finalHeight)
  } else {
    let heightLeft = imgHeight
    let position = 0
    pdf.addImage(imgData, "PNG", 0, position, imgWidth, imgHeight)
    heightLeft -= pageHeight
    while (heightLeft > 0) {
      position -= pageHeight
      pdf.addPage()
      pdf.addImage(imgData, "PNG", 0, position, imgWidth, imgHeight)
      heightLeft -= pageHeight
    }
  }

  pdf.save(filename)
}
