import type { AlignmentResult } from "./types"

// Escape special LaTeX characters.
function escapeLatex(str: string): string {
  return str
    .replace(/\\/g, "\\textbackslash{}")
    .replace(/([&%$#_{}])/g, "\\$1")
    .replace(/~/g, "\\textasciitilde{}")
    .replace(/\^/g, "\\textasciicircum{}")
}

/**
 * Generate an ATS-optimized LaTeX resume that mirrors the user's template.
 * Personal/contact details are intentionally omitted.
 */
export function generateLatexResume(result: AlignmentResult): string {
  const { resume } = result

  // Split skills into two categories so the section reads cleanly.
  const half = Math.ceil(resume.coreSkills.length / 2)
  const primarySkills = resume.coreSkills.slice(0, half).map(escapeLatex).join(", ")
  const secondarySkills = resume.coreSkills.slice(half).map(escapeLatex).join(", ")

  let skillsContent = ""
  if (primarySkills) {
    skillsContent += `\\textbf{Core Competencies:} ${primarySkills}`
    if (secondarySkills) skillsContent += " \\\\\n     "
  }
  if (secondarySkills) {
    skillsContent += `\\textbf{Supporting Skills:} ${secondarySkills}`
  }

  // Build experience entries.
  let experienceContent = ""
  resume.experiences.forEach((exp) => {
    experienceContent += `    \\resumeSubheading\n      {${escapeLatex(exp.company)}}{${escapeLatex(exp.period)}}\n      {${escapeLatex(exp.role)}}{}\n`
    experienceContent += `      \\resumeItemListStart\n`
    exp.bullets.forEach((bullet) => {
      const text = escapeLatex(bullet.text)
      experienceContent += bullet.emphasized
        ? `        \\resumeItem{\\textcolor{custom2}{${text}}}\n`
        : `        \\resumeItem{${text}}\n`
    })
    experienceContent += `      \\resumeItemListEnd\n`
  })

  return `%-------------------------
% ATS-Optimized Resume in LaTeX
% Generated by Semantic Career Alignment Engine
%------------------------

\\documentclass[letterpaper,11pt]{article}

\\usepackage{latexsym}
\\usepackage[empty]{fullpage}
\\usepackage{titlesec}
\\usepackage{marvosym}
\\usepackage[usenames,dvipsnames]{color}
\\usepackage{verbatim}
\\usepackage{enumitem}
\\usepackage[hidelinks]{hyperref}
\\usepackage{fancyhdr}
\\usepackage[english]{babel}
\\usepackage{tabularx}
\\usepackage{multicol}
\\setlength{\\multicolsep}{-3.0pt}
\\setlength{\\columnsep}{-1pt}
\\input{glyphtounicode}

\\definecolor{custom1}{RGB}{10, 48, 97}
\\definecolor{custom2}{RGB}{65,105,225}

\\pagestyle{fancy}
\\fancyhf{}
\\fancyfoot{}
\\renewcommand{\\headrulewidth}{0pt}
\\renewcommand{\\footrulewidth}{0pt}

\\addtolength{\\oddsidemargin}{-0.6in}
\\addtolength{\\evensidemargin}{-0.5in}
\\addtolength{\\textwidth}{1.19in}
\\addtolength{\\topmargin}{-.7in}
\\addtolength{\\textheight}{1.4in}

\\urlstyle{same}

\\raggedbottom
\\raggedright
\\setlength{\\tabcolsep}{0in}

\\titleformat{\\section}{
  \\vspace{-4pt}\\scshape\\raggedright\\large\\bfseries
}{}{0em}{}[\\titlerule \\vspace{-5pt}]

\\pdfgentounicode=1

%-------------------------
% Custom commands
\\newcommand{\\resumeItem}[1]{
  \\item\\small{
    {#1 \\vspace{-2pt}}
  }
}

\\newcommand{\\resumeSubheading}[4]{
  \\vspace{-2pt}\\item
    \\begin{tabular*}{1.0\\textwidth}[t]{l@{\\extracolsep{\\fill}}r}
      \\textbf{{#1}} & \\textbf{\\small #2} \\\\
      \\textit{\\small#3} & \\textit{\\small #4} \\\\
    \\end{tabular*}\\vspace{-7pt}
}

\\renewcommand\\labelitemi{$$\\vcenter{\\hbox{\\tiny$$\\bullet$$}}$$}
\\renewcommand\\labelitemii{$$\\vcenter{\\hbox{\\tiny$$\\bullet$$}}$$}

\\newcommand{\\resumeSubHeadingListStart}{\\begin{itemize}[leftmargin=0.0in, label={}]}
\\newcommand{\\resumeSubHeadingListEnd}{\\end{itemize}}
\\newcommand{\\resumeItemListStart}{\\begin{itemize}}
\\newcommand{\\resumeItemListEnd}{\\end{itemize}\\vspace{-5pt}}

%-------------------------------------------
%%%%%%  RESUME STARTS HERE  %%%%%%%%%%%%%%%%%%%%%%%%%%%%

\\begin{document}

%----------HEADING----------
\\begin{center}
    {\\LARGE \\scshape \\textcolor{custom1}{${escapeLatex(resume.name)}}} \\\\ \\vspace{2pt}
    \\small ${escapeLatex(resume.headline)}
    \\vspace{-5pt}
\\end{center}

%-----------PROFESSIONAL SUMMARY-----------
\\section{\\textcolor{custom1}{Professional Summary}}
    \\resumeSubHeadingListStart
    \\small{${escapeLatex(resume.summary)}}
    \\resumeSubHeadingListEnd

%-----------TECHNICAL SKILLS-----------
\\vspace{-13pt}
\\section{\\textcolor{custom1}{Technical Skills}}
 \\begin{itemize}[leftmargin=0.15in, label={}]
    \\small{\\item{
     ${skillsContent} \\\\
     }}
 \\end{itemize}

%-----------PROFESSIONAL EXPERIENCE-----------
\\vspace{-13pt}
\\section{\\textcolor{custom1}{Professional Experience}}
  \\resumeSubHeadingListStart
${experienceContent}  \\resumeSubHeadingListEnd

\\end{document}
`
}

export function downloadLatex(content: string, filename = "resume.tex"): void {
  const element = document.createElement("a")
  element.setAttribute("href", "data:text/plain;charset=utf-8," + encodeURIComponent(content))
  element.setAttribute("download", filename)
  element.style.display = "none"
  document.body.appendChild(element)
  element.click()
  document.body.removeChild(element)
}

// Theme colors as RGB tuples for the PDF.
const NAVY: [number, number, number] = [10, 48, 97]
const ROYAL: [number, number, number] = [37, 99, 235]
const BODY: [number, number, number] = [31, 41, 55]
const MUTED: [number, number, number] = [75, 85, 99]

/**
 * Generate a crisp, selectable, lightweight (compressed) vector PDF that
 * mirrors the LaTeX template layout. No rasterization — text stays sharp and
 * the file size stays tiny. Auto-scales font size to keep it to a single page.
 */
export async function generateResumePdf(result: AlignmentResult, filename = "resume.pdf"): Promise<void> {
  const { jsPDF } = await import("jspdf")
  const { resume } = result

  // A4 page, compression enabled for small file size.
  const pageW = 210
  const pageH = 297
  const marginX = 18
  const usableW = pageW - marginX * 2

  // Try progressively smaller scales until everything fits on one page.
  const scales = [1, 0.95, 0.9, 0.85, 0.8, 0.75, 0.7]
  for (let s = 0; s < scales.length; s++) {
    const scale = scales[s]
    const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4", compress: true })
    const fit = renderResume(doc, resume, { pageW, pageH, marginX, usableW, scale })
    if (fit || s === scales.length - 1) {
      doc.save(filename)
      return
    }
  }
}

type Resume = AlignmentResult["resume"]

function renderResume(
  doc: import("jspdf").jsPDF,
  resume: Resume,
  cfg: { pageW: number; pageH: number; marginX: number; usableW: number; scale: number },
): boolean {
  const { pageW, pageH, marginX, usableW, scale } = cfg
  const bottomLimit = pageH - 16
  let y = 20

  const fs = (pt: number) => pt * scale
  const lh = (pt: number) => (pt * scale) / 2.6 // approximate line height in mm

  // ---- Heading: name (centered, navy) ----
  doc.setFont("helvetica", "bold")
  doc.setFontSize(fs(22))
  doc.setTextColor(...NAVY)
  doc.text(resume.name.toUpperCase(), pageW / 2, y, { align: "center" })
  y += lh(22) + 1

  if (resume.headline) {
    doc.setFont("helvetica", "normal")
    doc.setFontSize(fs(10.5))
    doc.setTextColor(...ROYAL)
    doc.text(resume.headline, pageW / 2, y, { align: "center" })
    y += lh(10.5) + 2
  }

  const section = (title: string) => {
    y += 3
    doc.setFont("helvetica", "bold")
    doc.setFontSize(fs(12))
    doc.setTextColor(...NAVY)
    doc.text(title.toUpperCase(), marginX, y)
    y += 1.5
    doc.setDrawColor(...NAVY)
    doc.setLineWidth(0.4)
    doc.line(marginX, y, pageW - marginX, y)
    y += 4
  }

  const paragraph = (text: string, pt: number, color: [number, number, number], style: "normal" | "italic" | "bold" = "normal") => {
    doc.setFont("helvetica", style)
    doc.setFontSize(fs(pt))
    doc.setTextColor(...color)
    const lines = doc.splitTextToSize(text, usableW)
    for (const line of lines) {
      doc.text(line, marginX, y)
      y += lh(pt) + 0.6
    }
  }

  // ---- Professional Summary ----
  section("Professional Summary")
  paragraph(resume.summary, 10, BODY)

  // ---- Technical Skills ----
  const half = Math.ceil(resume.coreSkills.length / 2)
  const primary = resume.coreSkills.slice(0, half)
  const secondary = resume.coreSkills.slice(half)
  section("Technical Skills")

  const skillLine = (label: string, items: string[]) => {
    if (items.length === 0) return
    doc.setFontSize(fs(10))
    doc.setFont("helvetica", "bold")
    doc.setTextColor(...NAVY)
    const labelText = `${label}: `
    const labelW = (doc.getStringUnitWidth(labelText) * fs(10)) / 2.83
    doc.text(labelText, marginX, y)
    doc.setFont("helvetica", "normal")
    doc.setTextColor(...BODY)
    const lines = doc.splitTextToSize(items.join(", "), usableW - labelW)
    lines.forEach((line: string, i: number) => {
      doc.text(line, i === 0 ? marginX + labelW : marginX, y)
      if (i < lines.length - 1) y += lh(10) + 0.6
    })
    y += lh(10) + 1.4
  }
  skillLine("Core Competencies", primary)
  skillLine("Supporting Skills", secondary)

  // ---- Professional Experience ----
  section("Professional Experience")
  resume.experiences.forEach((exp, idx) => {
    // company (bold, left) + period (bold, right)
    doc.setFont("helvetica", "bold")
    doc.setFontSize(fs(11))
    doc.setTextColor(...BODY)
    doc.text(exp.company, marginX, y)
    doc.text(exp.period, pageW - marginX, y, { align: "right" })
    y += lh(11) + 0.6
    // role (italic)
    doc.setFont("helvetica", "italic")
    doc.setFontSize(fs(10))
    doc.setTextColor(...MUTED)
    doc.text(exp.role, marginX, y)
    y += lh(10) + 1
    // bullets
    exp.bullets.forEach((b) => {
      const color = b.emphasized ? ROYAL : BODY
      doc.setFont("helvetica", b.emphasized ? "bold" : "normal")
      doc.setFontSize(fs(10))
      doc.setTextColor(...color)
      const bulletIndent = marginX + 4
      const lines = doc.splitTextToSize(b.text, usableW - 4)
      doc.text("\u2022", marginX + 1, y)
      lines.forEach((line: string) => {
        doc.text(line, bulletIndent, y)
        y += lh(10) + 0.5
      })
    })
    if (idx < resume.experiences.length - 1) y += 2
  })

  return y <= bottomLimit
}
